version: "2"
services:
  node:
    build:
      context: .
    env_file: .env
    restart: always
    dns: '8.8.8.8'
    volumes:
      - ./tmp:/home/node/app/tmp
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

networks:
  default:
    external: true
    name: docker-vpn0
